#!/usr/bin/env bash
export PROJECT_ID=
export IAP_USER=  # mail id for the IAP user configuring
export NAMESPACE= # spinnaker deployed namespace name
export DOMAIN_PREFIX=spinnaker3
export HALYARD_VERSION=1.33.0
export SERVICE_ACCOUNT_NAME="$DOMAIN_PREFIX-sa-1586329621"
export STATIC_IP_NAME=$DOMAIN_PREFIX-external-ip
export MANAGED_CERT=$DOMAIN_PREFIX-managed-cert
export SECRET_NAME=$DOMAIN_PREFIX-oauth-client-secret
export DOMAIN_NAME=$DOMAIN_PREFIX.endpoints.$PROJECT_ID.cloud.goog
